[package]
name = "O2-hello-world-cargo-new"
version = "0.1.0"
authors = ["Shogo N <shogonir@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
